steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/cloudrun-sql/nginx:latest", "."]
- name: gcr.io/cloud-builders/docker
  args: ["push", "gcr.io/cloudrun-sql/nginx:latest"]
- name: gcr.io/cloud-builders/gcloud
  args: ['run', 'deploy', 'nginx', ' — image', 'gcr.io/cloudrun-sql/nginx', ' — port', '80', ' — region', 'us-central1', ' — platform', 'managed', ' — allow-unauthenticated']
images:
- gcr.io/cloudrun-sql/nginx:latest